# Generated by Django 5.2 on 2025-05-26 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CusID', models.AutoField(primary_key=True, serialize=False)),
                ('CusName', models.CharField(max_length=50)),
                ('MobileNo', models.IntegerField()),
                ('Email', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('DriverID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('MobileNo', models.IntegerField()),
                ('LicenseNo', models.CharField(max_length=255)),
                ('LicenseExpDate', models.DateField()),
                ('DateOfJoining', models.DateField()),
                ('TotalExperience', models.IntegerField()),
                ('Address', models.CharField(max_length=255)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('VehicleID', models.AutoField(primary_key=True, serialize=False)),
                ('VehicleRegNo', models.IntegerField(unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('RegistrationExpDate', models.DateField()),
                ('VehicleGroup', models.CharField(max_length=255)),
                ('VehicleColour', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Remainder',
            fields=[
                ('RemainderID', models.AutoField(primary_key=True, serialize=False)),
                ('RemDate', models.DateField()),
                ('Message', models.CharField(max_length=255)),
                ('VehicleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('BookId', models.AutoField(primary_key=True, serialize=False)),
                ('TripType', models.CharField(max_length=255)),
                ('StartLocation', models.CharField(max_length=255)),
                ('EndLocation', models.CharField(max_length=255)),
                ('ApproxKM', models.IntegerField()),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('TotalAmount', models.IntegerField()),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=8)),
                ('CusID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('DriverID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.driver')),
                ('VehicleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehicle')),
            ],
        ),
    ]
