# Generated by Django 5.2 on 2025-05-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='ReferenceNotes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='apiPassword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='apiUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='apiUsername',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
